name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize, converted_to_draft, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event_name}}'
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo '${{ github.sha }}'
      - run: echo '${{ github.ref }}'
      - run: echo '${{ github.base_ref }}'
      - run: echo '${{ github.head_ref }}'
